---
  - hosts: GoldenWasteDB
    gather_facts: false
    become: yes
    vars:
      new_mysql_root_password: DevOps@2022
      mysqlsoftware:
        - mysql-server
        - mysql-client

    tasks:
      - name: Install python, pip, MySQL etc.
        apt:
          name: "{{ packages }}"
          state: present
          update_cache: yes
        vars:
          packages:
            - python3-pip
            - python3-dev
            - default-libmysqlclient-dev
            - build-essential
            - mysql-server
            - mysql-client

      - name: pip install mysqlclient
        shell: pip install mysqlclient

      - name: Start the MySQL service
        action: service name=mysql state=started

      - name: Copy .my.cnf file with root password credentials
        template: src=/home/ubuntu/GoldenWaste/ansible/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

      - name: Update MySQL root password for all root accounts
        mysql_user:
          name: root
          host: "{{ item }}"
          password: "{{ new_mysql_root_password }}"
        with_items:
          - "{{ ansible_host }}"
          - 127.0.0.1
          - ::1
          - localhost

      - name: Delete anonymous MySQL server user for localhost
        action: mysql_user user="" state="absent"

      - name: Remove the MySQL test database
        action: mysql_db db=test state=absent

      - name: Remove   /root/.my.cnf
        ansible.builtin.file:
          path: /root/.my.cnf
          state: absent