---
  - hosts: GoldenWasteWebApp
    gather_facts: false
    tasks:

      - name: Install Java
        become: yes
        apt:
          name: openjdk-11-jdk
          state: present
          update_cache: yes

      - name: Set Linux environment variables
        shell: export GOLDEN_DB_URL=10.0.139.112
      
      - name: Set Linux environment variables
        shell: export GOLDEN_DB_PORT=3306

      - name: Set Linux environment variables
        shell: export GOLDEN_DB_NAME=goldenwastedb

      - name: Set Linux environment variables
        shell: export GOLDEN_DB_USERNAME=root
        
      - name: Set Linux environment variables
        shell: export GOLDEN_DB_PASSWORD=DevOps@2022